### PR TITLE
+ Added color palette

### PR DESCRIPTION
**Pull request by ShiroTohu**
## Description
I added the color palette for you as tailwind CSS variables. I'll also put these variables in the Figma file for future reference as well.

I haven't edited the body CSS at the moment, though on my local machine removing the variables doesn't change the look of the documentation.

let me know if you need anything changed.
meow_code

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [x] No, and this is why: Just tests for JavaScript right?
- [ ] I need help with writing tests

### CODE REVIEW

**Review by caffeine-addictt — CHANGES_REQUESTED** [review]
a2fba01 Should fix the styling issues

**Comment by ShiroTohu** [comment]
> [a2fba01](https://github.com/python-thread/thread.ngjx.org/commit/a2fba01010a5934ad7744025aa1a32f8a6ee98d5) Should fix the styling issues

My Apologies, my wording was a bit off. My styling is fine, the proposed changes have already been applied locally and tailwind functions normally. I've also added a linear gradient background to show the styling off.
Untitled

Let me know if I'm not understanding anything.

**Comment by caffeine-addictt** [comment]
Ahhh, got you

**Review by caffeine-addictt — APPROVED** [review]
LGTM!

**Pull request merged**
